### ISSUE TITLE
Crashing via TLauncher & CurseForge

### ISSUE THREAD

**Issue by ifallensyko** [JamStudios/DynamicClient#32]
Crashing via TLauncher & CurseForge when trying to add dynamic over ATM6 1.8.14 Forge - 36.2.20

even tried to remove the duplicate mods, either from dynamic or from ATM6
still end up with 6 mods failing to load 

- OS: Windows 10 (amd64) version 10.0

```
- https://pastebin.com/Ubbzs1At

- https://pastebin.com/9NCWSV3q
```

**Comment by JamTheAdventurer** [comment]
Hmm.. What Java/OpenJDK are you using?

**Comment by JamTheAdventurer** [comment]
It might have something to do with your Java/OpenJDK version, make sure the version is in Java/OpenJDK 8 - 11, If this does not work or you don't want to go back to the Java/OpenJDK 8 - 11 because of the Log4Shell Exploit.
We will be willingly forward this to the ForgeHax Devs if it doesn't work, as the mods that failed to load is forgehax.jar, this mod is not managed/owned by me, or our corporation, just asks us if you want to forward this to ForgeHax.

Says it on the front page in bold text: https://github.com/fr1kin/ForgeHax/wiki
Related Issue: https://github.com/fr1kin/ForgeHax/issues/392

**Comment by JamTheAdventurer** [comment]
*Also we recommend Deleting "C:\Users\%Username%\AppData\Roaming\.minecraft\versions\Dynamic Client" and Downloading the newer version (Major Update) of the dynamic client, to improve performance and to avoid mod clotting/flooding.
Update to: https://github.com/JamStudios/DynamicClient/releases/tag/v1.9.10
Reason: https://github.com/JamStudios/DynamicClient/wiki/Major-Update

**Comment by JamTheAdventurer** [comment]
ATM6 is a mod pack with a bunch of mods, I think you might have a thing called mod intersecting, it is possible that some of the ATM6's mods might have caused an issue, we do not recommend merging mods from another modpack to Dynamic Client, But if you want to still do it follow these steps:
- Seperate ATM6 Mods From the Dynamic Client's mod folder.
- Add 1 mod to the mod folder of Dynamic Client's mods.
- Run it, if it fails the mod that you have moved in the mods folder is not compatible with Dynamic Client., if it works fine, keep the mod in the mods folder and repeat the process to see what mod caused it.

**Comment by JamTheAdventurer** [comment]
This issue is now being closed, if the answers/solutions did not work, feel free to re-open this issue and explain what happened.

Reason: External Problem / Not Caused By Dynamic Client + solved.
